name: CI with Dependency Caching

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prime-cache-e15e741
        id: cache-step
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: cache-e15e741-${{ runner.os }}
          restore-keys: |
            cache-e15e741-

      - name: echo cache status
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" = 'true' ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi

